app_root/core/data_model/models.py
# The examples in this file come from the Flask-SQLAlchemy documentation
# For more information take a look at:
# http://flask-sqlalchemy.pocoo.org/2.1/quickstart/#simple-relationships

from datetime import datetime

from . import db


class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(80))
    body = db.Column(db.Text)
    pub_date = db.Column(db.DateTime)

    category_id = db.Column(db.Integer, db.ForeignKey('category.id'))
    category = db.relationship('Category', backref=db.backref('posts', lazy='dynamic'))

    def __init__(self, title, body, category, pub_date=None):
        self.title = title
        self.body = body
        if pub_date is None:
            pub_date = datetime.utcnow()
        self.pub_date = pub_date
        self.category = category

    def __repr__(self):
        return '<Post %r>' % self.title


class Category(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(50))

    def __init__(self, name):
        self.name = name

    def __repr__(self):
        return '<Category %r>' % self.name

app_root/api/__init__.py
from .endpoints.categories import ns as blog_categories_namespace
from .endpoints.posts import ns as blog_posts_namespace
from .restplus import api
from app_root.core import error_handlers
from flask import Blueprint
from flask_jsonschema import ValidationError


def get_blueprint():
    blueprint = Blueprint('api', __name__)
    api.init_app(blueprint)
    api.add_namespace(blog_posts_namespace)
    api.add_namespace(blog_categories_namespace)
    blueprint.register_error_handler(ValidationError, error_handlers.on_validation_error)

    return blueprint

app_root/app/__init__.py
from flask import Blueprint

app_root/app/views/home.py
from flask import Blueprint
from flask import make_response
from flask import render_template


bp_home = Blueprint('home', __name__)


@bp_home.route('/', methods=['GET'])
def index():
    return render_template('index.html')

app_root/app/views/register.py
from flask import Blueprint

bp_register = Blueprint('register', __name__)

app_root/app_config/__init__.py
from os import path
import logging.config

log_file_path = path.join(path.dirname(path.abspath(__file__)), 'logging.conf')
logging.config.fileConfig(log_file_path)
log = logging.getLogger(__name__)
basedir = path.abspath(path.dirname(__file__))

app_root/core/data_model/__init__.py
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()


def reset_database(db_instance, app_config):
    from app_root.core.data_model import models
    from app_root.core.data_model import auth

    db_instance.drop_all()
    db_instance.create_all()

app_root/core/data_model/auth.py
from flask_security import UserMixin, RoleMixin
from app_root.core.auth.encryption import EncryptionService
from sqlalchemy.ext.hybrid import hybrid_property
from sqlalchemy.orm import relationship, backref
from sqlalchemy import Column, DateTime, ForeignKey, Integer, String, text
from sqlalchemy.orm import relationship
from sqlalchemy.ext.declarative import declarative_base
from . import db


Base = declarative_base()
metadata = Base.metadata


class AddressType(Base):
    __tablename__ = 'address_type'

    address_type_id = Column(Integer, primary_key=True, unique=True)
    address_type_uuid = Column(String(36), nullable=False, unique=True)
    slug = Column(String(128), nullable=False, unique=True)
    display_name = Column(String(255), nullable=False, unique=True)
    description = Column(String(255))
    active = Column(Integer, nullable=False, server_default=text("'1'"))
    display = Column(Integer, nullable=False, server_default=text("'1'"))
    created_date = Column(DateTime, nullable=False)
    created_by = Column(ForeignKey('user.user_id'), nullable=False, index=True)
    modified_date = Column(DateTime)
    modified_by = Column(ForeignKey('user.user_id'), index=True)
    deactivated_date = Column(DateTime)
    deactivated_by = Column(ForeignKey('user.user_id'), index=True)
    valid_from_date = Column(DateTime, nullable=False)
    valid_to_date = Column(DateTime)

    user = relationship('User', primaryjoin='AddressType.created_by == User.user_id')
    user1 = relationship('User', primaryjoin='AddressType.deactivated_by == User.user_id')
    user2 = relationship('User', primaryjoin='AddressType.modified_by == User.user_id')


class ContactType(Base):
    __tablename__ = 'contact_type'

    contact_type_id = Column(Integer, primary_key=True, unique=True)
    contact_type_uuid = Column(String(36), nullable=False, unique=True)
    slug = Column(String(128), nullable=False, unique=True)
    display_name = Column(String(255), nullable=False, unique=True)
    description = Column(String(255))
    active = Column(Integer, nullable=False, server_default=text("'1'"))
    display = Column(Integer, nullable=False, server_default=text("'1'"))
    created_date = Column(DateTime, nullable=False)
    created_by = Column(ForeignKey('user.user_id'), nullable=False, index=True)
    modified_date = Column(DateTime)
    modified_by = Column(ForeignKey('user.user_id'), index=True)
    deactivated_date = Column(DateTime)
    deactivated_by = Column(ForeignKey('user.user_id'), index=True)
    valid_from_date = Column(DateTime, nullable=False)
    valid_to_date = Column(DateTime)

    user = relationship('User', primaryjoin='ContactType.created_by == User.user_id')
    user1 = relationship('User', primaryjoin='ContactType.deactivated_by == User.user_id')
    user2 = relationship('User', primaryjoin='ContactType.modified_by == User.user_id')


class Metadatum(Base):
    __tablename__ = 'metadata'

    tablename_id = Column(Integer, primary_key=True, unique=True)
    active = Column(Integer, nullable=False, server_default=text("'1'"))
    display = Column(Integer, nullable=False, server_default=text("'1'"))
    created_date = Column(DateTime, nullable=False)
    created_by = Column(Integer, nullable=False)
    modified_date = Column(DateTime)
    modified_by = Column(Integer)
    deactivated_date = Column(DateTime)
    deactivated_by = Column(Integer)
    valid_from_date = Column(DateTime, nullable=False)
    valid_to_date = Column(DateTime)


class Organization(Base):
    __tablename__ = 'organization'

    organization_id = Column(Integer, primary_key=True, unique=True)
    organization_uuid = Column(String(36), nullable=False, unique=True)
    parent_organization_id = Column(String(36), index=True)
    organization_type_id = Column(ForeignKey('organization_type.organization_type_id'), nullable=False, index=True)
    name = Column(String(255), nullable=False, unique=True)
    description = Column(String(255))
    active = Column(Integer, nullable=False, server_default=text("'1'"))
    display = Column(Integer, nullable=False, server_default=text("'1'"))
    created_date = Column(DateTime, nullable=False)
    created_by = Column(ForeignKey('user.user_id'), nullable=False, index=True)
    modified_date = Column(DateTime)
    modified_by = Column(Integer)
    deactivated_date = Column(DateTime)
    deactivated_by = Column(Integer)
    valid_from_date = Column(DateTime, nullable=False)
    valid_to_date = Column(DateTime)

    user = relationship('User')
    organization_type = relationship('OrganizationType')


class OrganizationAddres(Base):
    __tablename__ = 'organization_address'

    organization_address_id = Column(Integer, primary_key=True, unique=True)
    organization_address_uuid = Column(String(36), nullable=False, unique=True)
    organization_id = Column(ForeignKey('organization.organization_id'), nullable=False, index=True)
    address_type_id = Column(ForeignKey('address_type.address_type_id'), nullable=False, index=True)
    address_line_1 = Column(String(255), nullable=False, server_default=text("'1'"))
    address_line_2 = Column(String(255))
    city = Column(String(255), nullable=False)
    state_province = Column(String(128), nullable=False)
    country_id = Column(String(45))
    postal_code = Column(String(12), nullable=False)
    display = Column(Integer, nullable=False, server_default=text("'1'"))
    created_date = Column(DateTime, nullable=False)
    created_by = Column(ForeignKey('user.user_id'), nullable=False, index=True)
    modified_date = Column(DateTime)
    modified_by = Column(Integer)
    deactivated_date = Column(DateTime)
    deactivated_by = Column(Integer)
    valid_from_date = Column(DateTime, nullable=False)
    valid_to_date = Column(DateTime)

    address_type = relationship('AddressType')
    user = relationship('User')
    organization = relationship('Organization')


class OrganizationContact(Base):
    __tablename__ = 'organization_contact'

    organization_contact_id = Column(Integer, primary_key=True, unique=True)
    organization_contact_uuid = Column(String(36), nullable=False, unique=True)
    organization_id = Column(ForeignKey('organization.organization_id'), nullable=False, index=True)
    contact_type_id = Column(ForeignKey('contact_type.contact_type_id'), nullable=False, index=True)
    value = Column(String(255), nullable=False)
    active = Column(Integer, nullable=False, server_default=text("'1'"))
    display = Column(Integer, nullable=False, server_default=text("'1'"))
    created_date = Column(DateTime, nullable=False)
    created_by = Column(ForeignKey('user.user_id'), nullable=False, index=True)
    modified_date = Column(DateTime)
    modified_by = Column(Integer)
    deactivated_date = Column(DateTime)
    deactivated_by = Column(Integer)
    valid_from_date = Column(DateTime, nullable=False)
    valid_to_date = Column(DateTime)

    contact_type = relationship('ContactType')
    user = relationship('User')
    organization = relationship('Organization')


class OrganizationType(Base):
    __tablename__ = 'organization_type'

    organization_type_id = Column(Integer, primary_key=True, unique=True)
    organization_type_uuid = Column(String(36), nullable=False)
    slug = Column(String(128), nullable=False, unique=True)
    display_name = Column(String(255), nullable=False, unique=True)
    description = Column(String(255))
    active = Column(Integer, nullable=False, server_default=text("'1'"))
    display = Column(Integer, nullable=False, server_default=text("'1'"))
    created_date = Column(DateTime, nullable=False)
    created_by = Column(ForeignKey('user.user_id'), nullable=False, index=True)
    modified_date = Column(DateTime)
    modified_by = Column(Integer)
    deactivated_date = Column(DateTime)
    deactivated_by = Column(Integer)
    valid_from_date = Column(DateTime, nullable=False)
    valid_to_date = Column(DateTime)

    user = relationship('User')


class OrganizationUserRole(Base):
    __tablename__ = 'organization_user_role'

    organization_user_role_id = Column(Integer, primary_key=True, unique=True)
    organization_user_role_uuid = Column(String(36), nullable=False, unique=True)
    organization_id = Column(ForeignKey('organization.organization_id'), nullable=False, index=True)
    user_id = Column(ForeignKey('user.user_id'), nullable=False, index=True)
    role_id = Column(ForeignKey('role.role_id'), nullable=False, index=True)
    active = Column(Integer, nullable=False, server_default=text("'1'"))
    display = Column(Integer, nullable=False, server_default=text("'1'"))
    created_date = Column(DateTime, nullable=False)
    created_by = Column(ForeignKey('user.user_id'), nullable=False, index=True)
    modified_date = Column(DateTime)
    modified_by = Column(Integer)
    deactivated_date = Column(DateTime)
    deactivated_by = Column(Integer)
    valid_from_date = Column(DateTime, nullable=False)
    valid_to_date = Column(DateTime)

    user = relationship('User', primaryjoin='OrganizationUserRole.created_by == User.user_id')
    organization = relationship('Organization')
    role = relationship('Role')
    user1 = relationship('User', primaryjoin='OrganizationUserRole.user_id == User.user_id')


class Role(Base, RoleMixin):
    __tablename__ = 'role'

    role_id = Column(Integer, primary_key=True, unique=True)
    role_uuid = Column(String(36), nullable=False, unique=True)
    parent_role_id = Column(ForeignKey('role.role_id'), index=True)
    role_type_id = Column(ForeignKey('role_type.role_type_id'), nullable=False, index=True)
    display_name = Column(String(255), nullable=False, unique=True)
    description = Column(String(255))
    active = Column(Integer, nullable=False, server_default=text("'1'"))
    display = Column(Integer, nullable=False, server_default=text("'1'"))
    created_date = Column(DateTime, nullable=False)
    created_by = Column(ForeignKey('user.user_id'), nullable=False, index=True)

app_root/core/schemas/__init__.py
from os import path

jsonschema_dir = path.abspath(__file__)

app_root/templates/bootstrap_base.html
{% extends "bootstrap/base.html" %}

{% block title %}Flask Base App{% endblock %}

{% block head %}
{{ super() }}
{% endblock %}

{% block navbar %}
<div class="navbar navbar-inverse" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url_for('home.index') }}">Flasky</a>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
    {% for message in get_flashed_messages() %}
    <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
    </div>
    {% endfor %}

    {% block page_content %}
    {% endblock %}
</div>
{% endblock %}

{% block scripts %}
{{ super() }}
{% endblock %}

app_root/templates/form_base.html
<!DOCTYPE html>
<!--[if lt IE 9]><html class="lt-ie9"><![endif]-->
<!--[if gt IE 8]><!--><html lang="en"><!--<![endif]-->

<!-- site.url: https://www.basketdevil.com -->
<!-- site.baseurl:  -->
<!-- siteurl: https://www.basketdevil.com -->

<!-- Basic Page Needs
================================================== -->
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="google-site-verification" content="" />

<!-- Mobile Specific Metas
================================================== -->
  <meta name="HandheldFriendly" content="True">
  <meta name="MobileOptimized" content="320">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

<!-- Meta tags
================================================== -->

<!-- Twitter Card -->
<meta name="twitter:card" content="summary">

<!-- Creator -->
<meta name="twitter:creator" content="@basketdevil">
<!-- Title -->

  <title>Basket Devil: Shopping basket analysis for retailers | Home</title>
  <meta property="og:title" content="Basket Devil: Shopping basket analysis for retailers | Home" />
  <meta name="twitter:title" content="Basket Devil: Shopping basket analysis for retailers | Home">


<!-- Twitter Site -->
<meta name="twitter:site" content="@basketdevil" />

<!-- Description -->

  <meta name="description" content="Data science services supporting small retailers including free shopping basket analysis">
  <meta property="og:description" content="Data science services supporting small retailers including free shopping basket analysis" />
  <meta property="twitter:description" content="Data science services supporting small retailers including free shopping basket analysis" />

  <link rel="canonical" href="https://www.basketdevil.com/" />

<!--[if lt IE 9]>
  <script src="/assets/js/vendor/html5shiv.js"></script>
  <script src="/assets/js/vendor/respond.js"></script>
  <script src="/assets/js/vendor/selectivizr-min.js"></script>
<![endif]-->

<!-- Favicons
================================================== -->

  <!--  Touch icon for iOS 2.0+ and Android 2.1+ -->
<link rel="apple-touch-icon" sizes="57x57" href="/assets/img/favicons/apple-icon-57x57.png">
<link rel="apple-touch-icon" sizes="60x60" href="/assets/img/favicons/apple-icon-60x60.png">
<link rel="apple-touch-icon" sizes="72x72" href="/assets/img/favicons/apple-icon-72x72.png">
<link rel="apple-touch-icon" sizes="76x76" href="/assets/img/favicons/apple-icon-76x76.png">
<link rel="apple-touch-icon" sizes="114x114" href="/assets/img/favicons/apple-icon-114x114.png">
<link rel="apple-touch-icon" sizes="120x120" href="/assets/img/favicons/apple-icon-120x120.png">
<link rel="apple-touch-icon" sizes="144x144" href="/assets/img/favicons/apple-icon-144x144.png">
<link rel="apple-touch-icon" sizes="152x152" href="/assets/img/favicons/apple-icon-152x152.png">
<link rel="apple-touch-icon" sizes="180x180" href="/assets/img/favicons/apple-icon-180x180.png">
<link rel="icon" type="image/png" sizes="192x192"  href="/assets/img/favicons/android-icon-192x192.png">
<link rel="icon" type="image/png" sizes="32x32" href="/assets/img/favicons/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="96x96" href="/assets/img/favicons/favicon-96x96.png">
<link rel="icon" type="image/png" sizes="16x16" href="/assets/img/favicons/favicon-16x16.png">
<link rel="manifest" href="/assets/img/favicons/manifest.json">
<meta name="msapplication-TileColor" content="#ffffff">
<meta name="msapplication-TileImage" content="/assets/img/favicons/ms-icon-144x144.png">
<meta name="theme-color" content="#ffffff">
<!-- CSS =================================================== -->
{% block styles %}
  <link rel="stylesheet" href="/assets/css/main.css" media="all" />
  <link rel="stylesheet" href="/assets/css/print.css" media="print" />
{% endblock %}


  <body class="page-home">


      <a class="skipnav" href="#main-content">Skip to main content</a>
<header role="banner">
  <div class="site-navbar usa-grid">
    <button class="menu-btn">Menu</button>
    <a class="site-logo media_link" href="/">
      <img src="/assets/img/logos/tailicon.png" alt="Basket Devil logo" aria-hidden="true"></a>
      <img src="/assets/img/logos/bd-title.svg" alt="Basket Devil title">
    <nav role="navigation">




  <ul class="usa-accordion">

      <li>
    <a href="/sign-up/" ><span>Sign up</span></a>
  </li>
  <li>
    <a href="/login/" ><span>Login</span></a>
  </li>

</ul>
    </nav>
  </div>
</header>



{% block scripts %}
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/waypoints/2.0.3/waypoints.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery-ajaxchimp/1.3.0/jquery.ajaxchimp.min.js" type="text/javascript"></script>
<script src="/js/index.js"></script>
<script src="/js/lib/uswds.min.js"></script>
<script src="/js/sticky.js"></script>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-99930019-1', 'auto');
  ga('set', 'anonymizeIp', true);
  ga('set', 'forceSSL', true);
  ga('send', 'pageview');
</script>
{% endblock %}
  </body>
</html>

app_root/templates/index.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Basket Devil Login</title>
    <!-- Update the link path to where your stylesheet file is located. For example: /path/to/your/assets/css/lib/uswds.min.css -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
      <link rel="stylesheet" href="{{ url_for('static', filename='css/uswds.css') }}" media="all" />
  </head>
  <body class="layout-demo">
  <a class="usa-skipnav" href="#main-content">Skip to main content</a>

  <div class="usa-overlay"></div>
  <main class="usa-grid usa-section usa-content usa-layout-docs" id="main-content">
<form class="usa-form" method="post">
  <fieldset>
    <legend class="usa-drop_text">Sign in</legend>

    <label for="sign-in-username">Email address</label>
    <input id="sign-in-username" name="username" type="text" autocapitalize="off" autocorrect="off">

    <label for="sign-in-password">Password</label>
    <input id="sign-in-password" name="password" type="password">
    <p class="usa-form-note">
      <a title="Show password" href="javascript:void(0);"
          class="usa-show_password"
          aria-controls="sign-in-password">
        Show password</a>
    </p>

    <input type="submit" value="Sign in">

  </fieldset>
</form>
  </main>
  <footer class="usa-footer usa-footer-medium" role="contentinfo">
  </footer>
  <!-- Update the link path to where your JavaScript file is located. For example: /path/to/your/assets/js/lib/uswds.min.js -->
  <script src="{{ url_for('static', filename='js/lib/uswds.min.js') }}"></script>
  </body>
</html>